server:
  port: 9011

spring:
  application:
    name: account-service
  datasource:
    url: jdbc:postgresql://localhost/testcontainers
    username: test
    password: 123ewqasd
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show_sql: true
        use_sql_comments: true
    show-sql: true
    hibernate:
      ddl-auto: none
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest